### ISSUE TITLE
example - Event Study - chart: Average Cumulative Returns by Quantile

### ISSUE THREAD

**Issue by pavelstovicek** [stefan-jansen/alphalens-reloaded#8]
## Problem Description
The chart called "Average Cumulative Returns by Quantile" in examples - Event Study has y-axis values of Mean Return (bps) in range 296000-304000! It seems to me, it is too high to be realistic!

Or maybe it is just confusing, that the name of the chart is Average Cumulative Returns and y-axis is labeled Mean Returns?  

If I understand the chart correctly, returns over 0 periods should be always zero (there is always zero return for holding the asset for zero time period).

**Please provide a minimal, self-contained, and reproducible example:**
```
https://github.com/stefan-jansen/alphalens-reloaded/blob/main/alphalens/examples/event_study.ipynb
```

![image](https://user-images.githubusercontent.com/79935384/152040744-ba59f4c8-aae0-4052-9668-0bf2dbd1d1b2.png)

**Comment by stefan-jansen** [comment]
Looks like there's something wrong with the figure, and it displays the factor values (above 30 before '0' and below at '1'), not the returns. PRs to fix are welcome.

**Comment by vincpota** [comment]
I believe the problem is that `create_event_study_tear_sheet` takes the factor data and __returns__, not prices as you can see from the [doc](https://github.com/stefan-jansen/alphalens-reloaded/blob/main/src/alphalens/tears.py#L614). This is despite all jupyter notebooks stating the opposite. I think you should use `create_event_study_tear_sheet(factor_data, prices.pct_change())`
